### ISSUE TITLE
doc: semantic specificity

### ISSUE THREAD

**Issue by sean-freeman** [linux-system-roles/ha_cluster#187]
> doc: semantic specificity

Looking at the README with fresh eyes, I notice the word `Support` is used frequently. Given this is a community repository, I would anticipate there is no (paid-for) support of the code, and the correct word for inference (particularly when translated) should instead be `Compatibility` / `Compatible`.

Example:
```
See sbd(8) man page, section 'Configuration via environment' for their description.
Supported options are:
```

**Comment by richm** [comment]
Can you give me specific examples of where the word "support" in the README should be replaced with another word, and how to rephrase the context in which the word "support" appears to use another word?

The word "support" appears about 181 times in the various linux-system-roles README.md files, and possibly more in other role documentation and examples.  From looking at the context in which the word is used, such as "supported by the role", it does not explicitly state nor imply that there is some sort of SLA or some other guarantee of the ability to have someone on the hook for resolving technical issues with the software in a timely manner.  Some of the licenses used by the roles also have a statement about the technical supportability of the code.

If there a context in which the word "support" is used that could give the impression that "This thing is guaranteed to work by X third party within a specific time period" then I would say we need to fix that.  But IMO colloquial usage of the word "support" in the context of the linux-system-role README.md files does not imply that.

**Comment by sean-freeman** [comment]
Previous SBD example given in initial message, another would be `Supported OS: RHEL 8.3+, Fedora 31+` which would imply any usage of this community/upstream Ansible Role in combination with RHEL would be supportable - which it would not, as the end-user might be paying for RHEL but is not paying for this code.

I personally agree with your POV, but I would say we both have the ability to discern the difference as a) fluent English speakers b) high awareness of open-source code usage and SLAs.

It may not be so obvious to infer this difference, some may immediately assume that Support is given by a vendor. Given that 'Support' has dual meaning (i.e. works with + help provided if does not work) vs. 'Compatible with one meaning (i.e. should work with), we cannot also predict how that word is inferred or translated into other languages.

**Comment by richm** [comment]
https://github.com/linux-system-roles/ha_cluster/pull/188
