### ISSUE TITLE
Add support for SBD devices

### ISSUE THREAD

**Issue by stdevel** [linux-system-roles/ha_cluster#29]
In `tasks/cluster-enable-disable.yml` there is a comment that SBD is currently disabled because it is not supported, yet:

```
# The role does not support configuring SBD yet, therefore we always disable it
```

Are there plans to support it in the future? I'm using this role to setup RHEL HA and the official documentation mentions that SBD is supported by Red Hat.

**Comment by richm** [comment]
@tomjelinek what are the plans for SBD support?

**Comment by tomjelinek** [comment]
Adding support for SBD to the system role is a high priority task. It has not made it to the top of the TODO list yet, however.

**Comment by stdevel** [comment]
How do you plan to implement it? I implemented some `post_tasks` as workaround, maybe I can contribute?

**Comment by stdevel** [comment]
I felt free to show you what I already got in merge request #31. It is not completed, yet (see details in the PR) - but it already works for my environment.

**Comment by richm** [comment]
fixed by https://github.com/linux-system-roles/ha_cluster/pull/31
