### ISSUE TITLE
If ansible_hostname includes '_' the role fails with `invalid characters in salt`

### ISSUE THREAD

**Issue by spetrosi** [linux-system-roles/ha_cluster#46]
I am running the role against hosts with hostnames `primary_8_6` and `secondary_8_6`. The task `Set hacluster password` fails on both with the `invalid characters in salt` error. https://github.com/linux-system-roles/ha_cluster/blob/master/tasks/install-and-configure-packages.yml#L52 must do `replace('_','x')` too.
We also must examine what other symbols that might appear in hostnames are not allowed in salt.

**Comment by richm** [comment]
Valid internet hostnames should not contain the underscore `_` character

**Comment by spetrosi** [comment]
I didn't know that and hostnamectl did not stop me from doing this. The error message from the `user` module was unhelpful:
 
```
TASK [fedora.linux_system_roles.ha_cluster : Set hacluster password] *******************************************************************
Thursday 28 April 2022  17:11:18 +0200 (0:00:01.874)       0:00:08.521 ******** 
fatal: [primary-8.6]: FAILED! => {"msg": "invalid characters in salt. invalid characters in salt"}
fatal: [secondary-8.6]: FAILED! => {"msg": "invalid characters in salt. invalid characters in salt"}
```

Since underscore cannot be used in valid hostnames I think we can close this issue.
